version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: streamlit-debug
    volumes:
      - .:/src
    ports:
      - "6161:6161"
      - "5678:5678" # Port for debugging
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True # Optional: Set an environment variable to indicate debugging mode
    command: >
      bash -c "pip install debugpy && 
               python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m streamlit run src/main.py --server.port=6161 --server.address=0.0.0.0 --server.runOnSave=True"
    depends_on:
      - database

  database:
    image: mysql:9.0.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql:/var/lib/mysql
