version: '0.1'
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - FRONTEND_DEBUGGING_PORT=${FRONTEND_DEBUGGING_PORT}
    container_name: ${FRONTEND_CONTAINER_NAME}
    tty: true
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_DEBUGGING_PORT=${FRONTEND_DEBUGGING_PORT}
    command: 
      ["bash", "-c", "streamlit run app/main.py --server.port=${FRONTEND_PORT} --server.address=0.0.0.0 --server.runOnSave=True"]
    volumes:
      - ./src/frontend:/src
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_DEBUGGING_PORT=${BACKEND_DEBUGGING_PORT}
    container_name: ${BACKEND_CONTAINER_NAME}
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_DEBUGGING_PORT=${BACKEND_DEBUGGING_PORT}
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./src/backend:/src
    depends_on:
      - database

  database:
    image: mysql:9.0.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql:/var/lib/mysql
  
